Issue37 bolt api
subecho/KarmaChameleon pull request #38
Opened 2021-02-17 02:36 UTC by wrideout

Fixes #37 

Refactors KarmaChameleon to use the latest Slack Bolt API!

2021-02-17 03:34 UTC, wrideout commented
Also fixes #3

2021-02-18 05:45 UTC, wrideout commented
I believe this also fixes #3

2021-02-18 18:25 UTC, subecho requested changes
This is a good start, but I'm concerned about the lack of modularity in the `karma_chameleon.py` file. With the effort that we took rewriting the thing with the Bolt API, we might want to also want clean that up as well.

2021-02-18 22:34 UTC, wrideout commented on README.md
> +forwarding the port that the Flask server is running on to a publicly accessible URL. I used
No good reason other than I wasn't sure how that design would work with the API.  I will make the change.

2021-02-19 00:12 UTC, wrideout commented on karma_chameleon.py
> +# Karma Chameleon
This has been reflectored.

2021-02-19 00:21 UTC, wrideout commented on karma_chameleon.py
> +@app.command("/ec_leaderboard")
This needs to be put back... The command present now is debug I forgot to remove.

2021-02-22 04:37 UTC, subecho approved these changes

2021-02-22 04:38 UTC, merged